/* Stella Azure — Memory System Schema (idempotent, re-runnable).
   참고: lib/memory-db.mjs 가 런타임에 자동 생성하므로 수동 실행은 선택사항. */
IF OBJECT_ID('dbo.ST_USERS','U') IS NULL
CREATE TABLE dbo.ST_USERS (user_id NVARCHAR(128) NOT NULL PRIMARY KEY, email NVARCHAR(256) NULL,
  display_name NVARCHAR(128) NULL, auth_provider NVARCHAR(32) NOT NULL DEFAULT 'google',
  status NVARCHAR(16) NOT NULL DEFAULT 'active',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.ST_USER_PROFILE','U') IS NULL
CREATE TABLE dbo.ST_USER_PROFILE (user_id NVARCHAR(128) NOT NULL PRIMARY KEY, nickname NVARCHAR(128) NULL,
  preferred_language NVARCHAR(16) NOT NULL DEFAULT 'ko', occupation NVARCHAR(256) NULL, interests NVARCHAR(MAX) NULL,
  response_style NVARCHAR(64) NULL, ai_personality NVARCHAR(64) NULL, extra_json NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.ST_USER_MEMORY','U') IS NULL
CREATE TABLE dbo.ST_USER_MEMORY (memory_id BIGINT IDENTITY(1,1) PRIMARY KEY, user_id NVARCHAR(128) NOT NULL,
  memory_text NVARCHAR(MAX) NOT NULL, category NVARCHAR(64) NULL, app_scope NVARCHAR(32) NOT NULL DEFAULT 'shared',
  source NVARCHAR(32) NOT NULL DEFAULT 'user', confidence FLOAT NULL, is_active BIT NOT NULL DEFAULT 1,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_MEMORY_USER_ACTIVE')
CREATE INDEX IX_MEMORY_USER_ACTIVE ON dbo.ST_USER_MEMORY(user_id, is_active, updated_at DESC);
IF OBJECT_ID('dbo.ST_CHAT_HISTORY','U') IS NULL
CREATE TABLE dbo.ST_CHAT_HISTORY (chat_id NVARCHAR(128) NOT NULL PRIMARY KEY, user_id NVARCHAR(128) NOT NULL,
  title NVARCHAR(512) NULL, summary NVARCHAR(MAX) NULL, source NVARCHAR(32) NOT NULL DEFAULT 'stella',
  drive_file_id NVARCHAR(256) NULL, message_count INT NOT NULL DEFAULT 0, keywords NVARCHAR(MAX) NULL,
  model NVARCHAR(64) NULL, started_at DATETIME2 NULL, last_message_at DATETIME2 NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_CHAT_USER_TIME')
CREATE INDEX IX_CHAT_USER_TIME ON dbo.ST_CHAT_HISTORY(user_id, last_message_at DESC);
